version: "3"
services:
  editor:
    container_name: editor
    build:
      context: .
      dockerfile: ./zenn/Dockerfile
    ports:
      - 9999:8000
      - 8888:8888
    tty: true
    volumes:
      - ./:/public
    environment:
      TZ: Asia/Tokyo
    command: npx zenn
